### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by bryanvanwijk**
I think this completely working version can be merged?

### CODE REVIEW

**Comment by egedebruin** [comment]
It works completely indeed! I think it can be merged.

**Comment by jochem725** [comment]
There are some check style, PMD and findbugs violations. 
I'll fix them before we can merge.

**Comment by jochem725** [comment]
I've resolved some warnings, after someone checked if the game still functions as normal it can be merged.

**Comment by bryanvanwijk** [comment]
Everything still functions as normally, I will merge it

**Pull request merged**
