### PR TITLE
Logger core

### PR DESCRIPTION
**Pull request by doriandekoning**
This is the core for the logger. The logger classes are implemented. Now we only need to integrate the logger into the main packages. If I've got some time left tomorrow afternoon I'll look into writing the log file in another thread then the main tread, to make sure the program does not stall when writing a large log file.

### CODE REVIEW

**Comment by bryanvanwijk** [comment]
The code looks good, but there is a failing test. <bug, testing

**Comment by doriandekoning** [comment]
The failing test is because we cannot read/write files on travis. I'll look into that.

**Comment by doriandekoning** [comment]
Nevermind, my bad I forgot to push the log folder to the repository, should be fixed now.

**Comment by egedebruin** [comment]
Looks good, I will merge it.

**Comment by egedebruin** [comment]
It was merged in master, so I changed that. Now it is merged into develop and master is reverted.

**Pull request merged**
