### PR TITLE
Improve code

### PR DESCRIPTION
**Pull request by doriandekoning**
This is the description of the major refactor we are planning to do? Would you please look at this very critically at this as this effects the design of the system.

### CODE REVIEW

**Comment by jochem725** [comment]
Wouldn't it be better to rename the subclasses of UiElement to UiElementSpaceShip instead of UiSpaceship for instance? Because that would make it more clear that SpaceShip is an element of the UI and not a UI itself.

**Comment by doriandekoning** [comment]
Good point, I'll change it. Some class names do become really long then though, long classnames is less of a problem then vague classnames

**Comment by bryanvanwijk** [comment]
I think this is a good refactoring to do.

**Comment by doriandekoning** [comment]
Can you take a look at this change, if its approved I think we should move this in develop.

**Comment by bryanvanwijk** [comment]
Looks good, I like the idea of an interface for moving units.

**Comment by jochem725** [comment]
Using interfaces is a great solution. Maybe you could rewrite some sentences in a more formal way (don't use "we" for example). After that has been changed, I agree with merging.

**Comment by doriandekoning** [comment]
For these documents I strongly disagree with you, these are all documents we use just in our team. They don't have to be super formal. I think its okay to use we in this context because these are documents describing what we are going to do.

**Comment by bryanvanwijk** [comment]
I agree with Dorian, to keep this documents like this.

**Pull request merged**
