### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by jochem725**
I think we are ready to merge our final version for this sprint.

### CODE REVIEW

**Comment by doriandekoning** [comment]
Seems fine if you ask me...

**Comment by egedebruin** [comment]
I agree with Bryan.

**Comment by doriandekoning** [comment]
nevermind I spoke to early, nullpointers are thrown when logging an event. As a result of that the log is not stored to a file.

**Comment by doriandekoning** [comment]
Should be fixed now.

**Comment by bryanvanwijk** [comment]
I think you can merge it

**Comment by jochem725** [comment]
It has indeed been fixed. It can now be merged.

**Pull request merged**
