### PR TITLE
Improve code

### PR DESCRIPTION
**Pull request by doriandekoning**

### CODE REVIEW

**Comment by egedebruin** [comment]
Great!

**Comment by bryanvanwijk** [comment]
Why are there almost empty new classes in this branch?
- I think this should be merged in develop not in master!

**Comment by doriandekoning** [comment]
Whoops only the pdf and tex files should be merged and indeed should be merged into develop...  It's definitely time for weekend.  I'll fix this in a minute.

**Comment by doriandekoning** [comment]
Wrong branch opening new pull request.

**Pull request closed without merging**
