### PR TITLE
Uml practice <documentation

### PR DESCRIPTION
**Pull request by jochem725**
I've finished exercise 2 and the sequence diagram of exercise 1.
Please look at them carefully because I was not sure about every answer.

### CODE REVIEW

**Comment by bryanvanwijk** [comment]
It looks good, maybe you can add to the Sequence diagram some examples of key events? <documentation

**Comment by doriandekoning** [comment]
The text seems fine, the sequence diagram however seems to miss some things like the GameUiController that ticks the game from the animation loop for example. For now the diagram doesn't show much except for the creation of objects.

<documentation

**Comment by jochem725** [comment]
I do agree with both of you, but the diagram is about the interactions between the different classes.
I'm not sure if we should make it more complicated. 
If I add game ticks for example, the diagram will no longer be sequential.

The same holds for key events, because they do not happen in a particular order.

**Comment by doriandekoning** [comment]
On the smaller things like key events I agree with Jochem but I think the tick method in the game class (and interactions with other classes through this tick method) are an important to show in a sequence diagram. Because these are indeed events that happen in a particular order, only n times a second. But maybe we should make a sequence diagram dedicated to the tick method, where this diagram is more focused on initialization of/starting the game. If you look for on the internet for examples of sequence diagrams, there are examples where important other interactions between classes are drawn too. 

However this is one of the main problems of UML, where to stop adding more details to prevent it the diagram from becoming a mess. 
<documentation

**Comment by jochem725** [comment]
I agree with you on the n times a second.
But the game animation is already ticking before it is started by the player.
This makes it a separate sequence, just like you suggested.

Because the exercise only asks for a diagram between our main classes, I don't think it is necessary to add this diagram about ticks, because the tick method heavily relies on units, which aren't main classes.

I'll add a reference to the tick method though, because I think it is important to mention this relation

**Comment by doriandekoning** [comment]
Looks fine now, but there is one (very) little thing I would add, an arrow to indicate the fact that the tick happens in a loop not just a single time.

**Pull request merged**
