### PR TITLE
Logger async <feature

### PR DESCRIPTION
**Pull request by doriandekoning**
This allows for writing changes to the log file on another thread, this makes sure the game does not get slowed down by writing to the disk.

### CODE REVIEW

**Comment by jochem725** [comment]
After investiragion, the failure seems to be caused by the log folder missing from the mvn target folder. <bug

**Comment by jochem725** [comment]
I've tried to fix the failing test, but I couldn't resolve it.
The cause of the error is with the travis log file path. Once I'll find a solution, I will push it so there is a test for logging to the file. 

If everyone agrees, this can now be merged.<bug

**Comment by bryanvanwijk** [comment]
Yes you can merge it

**Comment by egedebruin** [comment]
I agree

**Comment by jochem725** [comment]
I came up with a solution, the error was in the reading of the file.

**Pull request merged**
