### PR TITLE
Fix for losing another life when hit during explosion <bug

### PR DESCRIPTION
**Pull request by bryanvanwijk**

### CODE REVIEW

**Comment by doriandekoning** [comment]
Is this related to the issue I posted a while ago where the player would loose multiple lives but I was not able to reproduce? Or was this introduced recently? Anyway seems like a good fix.

**Comment by jochem725** [comment]
I saw it today, but could not reproduce it. Perhaps it would be better to find the source of the problem. This looks like a good fix, but maybe it would be better to separate player death and explosions in some way.

**Comment by doriandekoning** [comment]
I agree exactly what Jochem says. I think the way player death and explosion are dependent on each other is a very strange approach.

**Comment by bryanvanwijk** [comment]
Do you think it would be better to have the spaceship disappear directly after it is hit?
And have immediately the spaceship respawned while the explosion is still going on?
Or would it be better to remember in the controller there is an explosion going on, with a spaceship and after this explosion is finished the ship is respawned? And let the spaceship during the explosion have his invulnerablitiy.

**Comment by jochem725** [comment]
I think the first option would be better, since an Alien also disappears immediately after being hit. 
This also removes the threat of potential bugs in the future by keeping this simple.

**Comment by bryanvanwijk** [comment]
I changed this in the latest commit.

**Comment by doriandekoning** [comment]
Great I think this simplification will prevent us from a lot of bugs in the future. You can merge this if one more person approves.

**Comment by jochem725** [comment]
Nice solution, I'll merge it.

**Pull request merged**
