### PR TITLE
Logger

### PR DESCRIPTION
**Pull request by egedebruin**
Implemented the logger into the game.

### CODE REVIEW

**Comment by doriandekoning** [comment]
The things you have implemented seem fine and can be merged into develop, however you also missed a lot of things that could be logged. For example, when creating the canvas it would be use full to print the size of the canvas. This will partly come overtime when refactoring the system but if you have got some time left you could try implementing some more logging .

**Comment by egedebruin** [comment]
I implemented some more messages in the code.

**Comment by jochem725** [comment]
Looks nice, I'll agree with merging.

**Comment by bryanvanwijk** [comment]
Looks good!

**Pull request merged**
