### PR TITLE
Crumbling barricades

### PR DESCRIPTION
**Pull request by doriandekoning**
I implemented barricade crumbling. Bullets don't collide with damaged parts of the barricade. The code is not super thoroughly tested since the crumbling  is (pseudo) random. To test this thoroughly  would consume a lot of time. The most critical parts for a good functioning game are (unit) tested however.

### CODE REVIEW

**Comment by jochem725** [comment]
Looks great! Sometimes the barricade seems to hang the game for a small moment (due to the calculation?).

Also the check style error can be resolved by refactoring, this way UIBarricade has different behavior as UIElementUnit, which should not be the case in SOLID. Also PMD reports some useless parenthesis which can be removed.

After this has been resolved I agree with merging.

**Comment by bryanvanwijk** [comment]
I agree with Jochem, If that is fixed it can be merged.

**Comment by doriandekoning** [comment]
First of all, the "useless" parentheses I'll look into them once more but I think they increase readability of the code.

 The other thing it seems to hang is indeed a problem, I've got no problem on my machine but I can reproduce it on my laptop after further investigation. I've got a fix in mind so I'll post that in a second.

What do you mean by "refactoring" the checkstyle error? Fixing this error would mean changing 5+ classes. If you're talking about the draw method in UIBarricade I would like to argue with you about the fact it violates SOLID the way it is at the moment. Because the draw method does the same thing as the draw method (in UIElementUnit) specification specifies. It draws a barricade object on the canvas.

**Comment by doriandekoning** [comment]
I updated a possible fix, it works for me but can one of you guys please confirm this?

**Comment by bryanvanwijk** [comment]
Great fix, it works much better, I fixed a small checkstyle warning for you.
I think it can be merged.

**Comment by doriandekoning** [comment]
Whoops that one slipped through, thank you!

**Comment by jochem725** [comment]
I think the Checkstyle violation can be solved easily by refactoring the drawUnit() method to drawUnitBarricade() or something like that, and call this method in the draw() method instead of drawUnit(). Since the behavior of the overridden drawUnit is different in the way a unit is drawn.

**Comment by doriandekoning** [comment]
The behaviour is not changed from the outside. Sure the way it draws is it is different on the inside.

**Comment by doriandekoning** [comment]
Fixed the checkstyle validation.

**Comment by bryanvanwijk** [comment]
Great, I think this can be merged!

**Comment by jochem725** [comment]
Great! This can be merged now.

**Pull request merged**
