### PR TITLE
Sound effects

### PR DESCRIPTION
**Pull request by jochem725**
I've implemented soundEffects and added toggle buttons to the main menu.

### CODE REVIEW

**Comment by jochem725** [comment]
I'm sorry for the huge amount of build failures which occurred finding the source of 115 test failures. This has been resolved by catching an exception caused by loading mp3 files, solving problems for computers without MP3 support.

**Comment by bryanvanwijk** [comment]
Sounds very good!

**Comment by egedebruin** [comment]
Sounds great indeed! I agree with merging

**Comment by doriandekoning** [comment]
Sounds good! You can merge it.

**Comment by jochem725** [comment]
Ok, I'll merge it!

**Pull request merged**
