### PR TITLE
The core

### PR DESCRIPTION
**Pull request by bryanvanwijk**
I made exercise 1.1 - 1.4

### CODE REVIEW

**Comment by jochem725** [comment]
There are small spelling errors throughout the text. 
Maybe these should be fixed before merging. <layout

**Comment by jochem725** [comment]
Shouldn't the relations between Game and the other classes be compositions? Because the Game can no longer function without these classes. <documentation, organisation

**Comment by bryanvanwijk** [comment]
I fixed some spelling error's, rewrote the sentence you mentioned and changed the relations in the UML. Did I still missed some spelling errors?

**Comment by doriandekoning** [comment]
Seems fine.
<documentation

**Comment by jochem725** [comment]
Thanks for fixing the errors.
By rewriting sentences containing "we", 
I mean writing in a formal way, like in the MAS Project report.

Like the first sentence:
"We followed the responsibility driven design by starting with the requirements."

becomes
"During this exercise, responsibility driven design was followed, starting with the requirements."

The UML diagram looks great now!
<documentation

**Comment by bryanvanwijk** [comment]
Thanks for your feedback. 
I have now rewritten the sentences in a more formal way.
Is it ready to merge now or do I have missed something?
<documentation

**Comment by jochem725** [comment]
Great! Is it true that it should be merged in master and not in develop?

**Comment by bryanvanwijk** [comment]
Yes, I branched it from master

**Comment by doriandekoning** [comment]
Why would you do that?

**Comment by bryanvanwijk** [comment]
Because I thought I wouldn't change anything on the development of the code so I could branch it from master. But if you would like to merge it in develop it's also fine with me?

**Pull request closed without merging**
