### PR TITLE
Checkstyle fixes

### PR DESCRIPTION
**Pull request by doriandekoning**
Fixed checkstyle errors.
<layout

### CODE REVIEW

**Comment by jochem725** [comment]
I've fixed the last 2 check style errors. I agree with merging now.

**Comment by bryanvanwijk** [comment]
Seems fine!

**Comment by jochem725** [comment]
This should fix the null pointer error I've introduced.
If everyone agrees with this fix, it can be merged.

**Comment by egedebruin** [comment]
I agree

**Pull request merged**
